//! Balance — Leptos CSR frontend.
//!
//! This crate replaces the original Vue + Vite frontend: it is a `cdylib`
//! compiled to `wasm32-unknown-unknown` and bundled by Trunk (see `Cargo.toml`
//! and `Trunk.toml` in this package).  `index.html` loads the `@tauri-apps/api`
//! module at runtime and exposes it as `window.__TAURI__`; [`services`] bridges
//! to it.  The module layout mirrors the old `src/` tree: [`models`] re-declares
//! the backend wire types, [`contexts`] replaces the Pinia stores and the
//! data composables, [`components`] replaces the SFCs and [`pages`] the root
//! view.

mod components;
mod contexts;
mod models;
mod pages;
mod services;

use leptos::mount::mount_to_body;
use leptos::prelude::*;
use wasm_bindgen::prelude::wasm_bindgen;

/// WASM entry point invoked by the page generated by Trunk.
#[wasm_bindgen(start)]
pub fn start() {
  console_error_panic_hook::set_once();
  mount_to_body(|| view! { <pages::app::App /> });
}
